Traceback (most recent call last):
  File "your_script.py", line 3, in <module>
    raise Exception("This will show up in your error.log file")
Exception: This will show up in your error.log file
